# regex.pyi
from typing import List, Optional, Any, Iterable, Iterator, Sequence, TypeVar

def findall_captures_str(pattern: str, text: str) -> List[List[Optional[str]]]: ...
def findall_captures_named_str(pattern: str, text: str) -> List[Any]: ...
def findall_captures_list_parallel(pattern: str, texts: List[str]) -> List[List[List[Optional[str]]]]: ...
def findall_captures_list(pattern: str, texts: List[str]) -> List[List[List[Optional[str]]]]: ...
def findall_captures_named_list_parallel(pattern: str, texts: List[str]) -> List[List[Any]]: ...
def find_joined_matches_in_file(pattern: str, file_path: str, groups: list[int]|None) -> list[str]: ...
def find_joined_matches_in_file_by_line_parallel(pattern: str, file_path: str, groups: list[int]|None) -> list[str]: ...
def find_joined_matches_in_file_by_line_bytes_parallel(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...
def find_joined_matches_in_file_by_line_bytes(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...
def extract_fixed_spans(file_path: str, start_delim: str, start_index: Optional[int], end_delim: Optional[str], end_index: Optional[int],
                        omit_first: Optional[int], omit_last: Optional[int], print_line_on_match: bool, case_insensitive: bool) -> list[str]: ...
def count_string_occurrences(items: list[str]) -> list[tuple[str, int]]: ...
def extract_fixed_spans_parallel(file_path: str, start_delim: str, start_index: Optional[int], end_delim: Optional[str], end_index: Optional[int],
                                 omit_first: Optional[int], omit_last: Optional[int], print_line_on_match: bool, case_insensitive: bool) -> list[str]: ...
def extract_fixed_lines(file_path: str, pattern: str, case_insensitive: bool) -> list[str]: ...
def extract_fixed_lines_parallel(file_path: str, pattern: str, case_insensitive: bool) -> list[str]: ...
def total_count(pattern: str, file_path: str, parallel: bool) -> list[str]: ...
def total_count_fixed_str(pattern: str, file_path: str, parallel: bool, case_insensitive: bool) -> list[str]: ...


class RustRegexGen:
    """
    RustRegexGen(pattern: str, iterable_of_strings: Iterable[str])

    A generator that yields one match (as a list of Optional[str]) at a time,
    across all input strings. Index 0 is the full match; index 1.. are capture groups.
    """

    def __init__(self, pattern: str, iterable_of_strings: Iterable[str]) -> None: ...
    def __iter__(self) -> Iterator[List[Optional[str]]]: ...
    def __next__(self) -> List[Optional[str]]: ...


class FileRegexGen(Iterator[str]):
    """
    FileRegexGen(pattern: str, filename: str) -> FileRegexGen

    Memory‐maps `filename` and yields exactly the group-1 capture (as `str`)
    for each match of `pattern`.  Raises StopIteration when done.
    """

    def __init__(self, pattern: str, filename: str) -> None: ...
    def __iter__(self) -> FileRegexGen: ...
    def __next__(self) -> str: ...

def from_file_range(pattern: str, filename: str, start: int, end: int) -> FileRegexGen: ...


# ---------------------------------------------------------------------------
# re-compatible drop-in API
# ---------------------------------------------------------------------------

# Flag constants re-exported from the Rust module (mirror re.IGNORECASE etc.).
I: int
IGNORECASE: int
M: int
MULTILINE: int
S: int
DOTALL: int


class PyMatch:
    """A `re.Match`-compatible object returned by search/match/fullmatch/finditer."""

    @property
    def string(self) -> str: ...
    @property
    def pos(self) -> int: ...
    @property
    def endpos(self) -> int: ...
    @property
    def lastindex(self) -> Optional[int]: ...
    @property
    def lastgroup(self) -> Optional[str]: ...
    @property
    def pattern(self) -> str: ...
    @property
    def flags(self) -> int: ...

    def start(self, group: Optional[Any] = None) -> int: ...
    def end(self, group: Optional[Any] = None) -> int: ...
    def span(self, group: Optional[Any] = None) -> tuple[int, int]: ...
    def group(self, *args: Any) -> Any: ...
    def groups(self, default: Optional[Any] = None) -> tuple[Any, ...]: ...
    def groupdict(self, default: Optional[Any] = None) -> dict[str, Any]: ...

    def __getitem__(self, key: Any) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> "PyMatchIter": ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...


class PyMatchIter:
    """Iterator over a Match's groups (group 0 excluded), as in `for g in m:`."""

    def __iter__(self) -> "PyMatchIter": ...
    def __next__(self) -> Any: ...


class PyFindIter:
    """Iterator of `PyMatch` returned by `finditer()`/`Pattern.finditer()`."""

    def __iter__(self) -> "PyFindIter": ...
    def __len__(self) -> int: ...
    def __next__(self) -> Optional[PyMatch]: ...


class PyPattern:
    """A `re.Pattern`-compatible compiled regex."""

    @property
    def pattern(self) -> str: ...
    @property
    def flags(self) -> int: ...
    @property
    def groups(self) -> int: ...

    def groupindex(self) -> dict[str, int]: ...

    def search(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> PyMatch: ...
    def match(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> PyMatch: ...
    def fullmatch(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> PyMatch: ...
    def findall(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> list[Any]: ...
    def finditer(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> PyFindIter: ...
    def findall_captures(self, string: str, pos: int = 0, endpos: Optional[int] = None) -> list[tuple[Optional[str], ...]]: ...
    def findall_captures_named(self, string: str) -> list[dict[str, Optional[str]]]: ...
    def sub(self, repl: Any, string: str, count: int = 0) -> str: ...
    def subn(self, repl: Any, string: str, count: int = 0) -> tuple[str, int]: ...
    def split(self, string: str, maxsplit: int = 0) -> list[Any]: ...
    def is_match(self, string: str, pos: int = 0) -> bool: ...
    def count(self, string: str) -> int: ...

    def __repr__(self) -> str: ...


# --- Minimal bytes API -----------------------------------------------------
# Mirrors `re.compile(bytes)` over `bytes`-like haystacks (bytes, bytearray,
# memoryview, mmap). Designed for `mmap_reader` so the mmap is searched in
# place without a UTF-8 -> str decode. Subset of the str API: enough for the
# file-scan path -- search, finditer, findall_captures, count, is_match.
class PyBytesMatch:
    """A `re.Match`-compatible object for bytes haystacks."""

    @property
    def pos(self) -> int: ...
    @property
    def endpos(self) -> int: ...
    @property
    def lastindex(self) -> Optional[int]: ...
    @property
    def pattern(self) -> bytes: ...
    @property
    def flags(self) -> int: ...

    def start(self, group: int = 0) -> int: ...
    def end(self, group: int = 0) -> int: ...
    def span(self, group: int = 0) -> tuple[int, int]: ...
    def group(self, *args: int) -> Optional[bytes] | tuple[Optional[bytes], ...]: ...
    def groups(self, default: Optional[bytes] = None) -> tuple[Optional[bytes], ...]: ...

    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...


class PyBytesFindIter(Iterator[PyBytesMatch]):
    """Lazy iterator: each `__next__` advances a cursor via `captures_at`,
    so peak memory is one match at a time plus the caller's buffer."""
    def __iter__(self) -> Iterator[PyBytesMatch]: ...
    def __next__(self) -> PyBytesMatch: ...


#: Type alias for any Python object exposing the 1-D bytes buffer protocol
#: (bytes, bytearray, memoryview, mmap.mmap). Matching `re.Pattern[bytes]`.
BytesLike = bytes | bytearray | memoryview  # actually any buffer-protocol object


class PyBytesPattern:
    """A subset of `re.Pattern[bytes]` sufficient for the file-scan CLI path."""

    @property
    def pattern(self) -> bytes: ...
    @property
    def flags(self) -> int: ...
    @property
    def groups(self) -> int: ...

    def search(self, haystack: BytesLike) -> PyBytesMatch: ...
    def finditer(self, haystack: BytesLike) -> PyBytesFindIter: ...
    def findall_captures(self, haystack: BytesLike) -> list[tuple[Optional[bytes], ...]]: ...
    def count(self, haystack: BytesLike) -> int: ...
    def is_match(self, haystack: BytesLike) -> bool: ...

    def __repr__(self) -> str: ...


# Module-level functions mirroring re.search/match/fullmatch/findall/
# finditer/sub/subn/split/compile.
def compile(pattern: str, flags: int = 0) -> PyPattern: ...
def compile_bytes(pattern: bytes, flags: int = 0) -> PyBytesPattern: ...
def search_re(pattern: str, string: str, pos: int = 0, endpos: Optional[int] = None, flags: int = 0) -> PyMatch: ...
def match(pattern: str, string: str, pos: int = 0, endpos: Optional[int] = None, flags: int = 0) -> PyMatch: ...
def fullmatch_re(pattern: str, string: str, pos: int = 0, endpos: Optional[int] = None, flags: int = 0) -> PyMatch: ...
def findall_re(pattern: str, string: str, pos: int = 0, endpos: Optional[int] = None, flags: int = 0) -> list[Any]: ...
def finditer_re(pattern: str, string: str, pos: int = 0, endpos: Optional[int] = None, flags: int = 0) -> PyFindIter: ...
def sub_re(pattern: str, repl: Any, string: str, count: int = 0, flags: int = 0) -> str: ...
def subn_re(pattern: str, repl: Any, string: str, count: int = 0, flags: int = 0) -> tuple[str, int]: ...
def split_re(pattern: str, string: str, maxsplit: int = 0, flags: int = 0) -> list[Any]: ...
def purge() -> bool: ...
