# regex.pyi
from typing import List, Optional, Any

class Regex:
    def __init__(self, pattern: str) -> None: ...
    def search(self, text: str) -> Optional["Match"]: ...

class Match:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def group(self) -> str: ...

def compile(pattern: str) -> Regex: ...
def search(pattern: str, text: str) -> Optional[Match]: ...
def findall_captures_str(pattern: str, text: str) -> List[List[Optional[str]]]: ...
def findall_captures_named_str(pattern: str, text: str) -> List[Any]: ...
def findall_captures_list_parallel(pattern: str, texts: List[str]) -> List[List[List[Optional[str]]]]: ...
def findall_captures_list(pattern: str, texts: List[str]) -> List[List[List[Optional[str]]]]: ...
def findall_captures_named_list_parallel(pattern: str, texts: List[str]) -> List[List[Any]]: ...
def find_joined_matches_in_file(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...
def find_joined_matches_in_file_by_line_parallel(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...
def find_joined_matches_in_file_by_line_bytes_parallel(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...
def find_joined_matches_in_file_by_line_bytes(pattern: str, file_path: str, groups: list[int]) -> list[str]: ...